### ISSUE TITLE
Setting derived value overrides derived handler

### ISSUE THREAD

**Issue by timuric** [pmndrs/valtio#245] opened 2021-09-28 15:17 UTC
Is the example bellow works as expected or should valtio make derived properties read only?

```js
// create a base proxy
const state = proxy({
  count: 1
});

// create a derived proxy
const derived = derive({
  double: (get) => get(state).count * 2
});

console.log("Expect 2", derived.double);
//Set to 4
derived.double = 4;
//Equals 4 but should be 8
console.log("Expect 8", derived.double);
```

[Link to playground ](https://codesandbox.io/s/valtio-simple-counter-forked-el7l7?file=/src/App.js)

**Comment by dai-shi** [comment] 2021-09-28 15:48
valtio state is really just an object by design. If we made it read-only, `derive` couldn't update the property either.
(I know, it's technically possible with set handler, but not by design.)

You might be interested in `proxyWithComputed` as the property will be read-only by default. (But, it has more pitfalls than `derive`.)

**Comment by timuric** [comment] 2021-09-28 15:54
@dai-shi I guess the return type of derive could be something like ```State & Readonly<Derived>```?

**Comment by dai-shi** [comment] 2021-09-28 15:59
For TS, yeah, that might be possible. But, from the library perspective, it's not correct type. So, I guess it's up to developers to assert read-only type.

**Comment by dai-shi** [comment] 2021-11-05 23:59
Closing as it's intended.

**Closed by dai-shi** 2021-11-05 23:59 UTC
