### ISSUE TITLE
DevTools: duplication of stores

### ISSUE THREAD

**Issue by Yanivba18** [pmndrs/valtio#302] opened 2021-12-29 13:11 UTC
Hi,
Creating a store using `proxy` and then adding it to `devtools` is causing a weird bug where stores are duplicated when viewing in Redux chrome extension.

This is the code I'm using to create the store:
```typescript
import { proxy } from 'valtio';
import { devtools } from 'valtio/utils';
import { isProduction } from './env-utils';

export const createStore: <T extends ObjectOf<T>>(
  initialObject: T,
  storeName: string,
) => T = (initialObject, storeName: string) => {
  const store = proxy(initialObject);

  if (!isProduction()) {
    devtools(store, storeName);
  }
  return store;
};

// https://github.com/typescript-eslint/typescript-eslint/issues/2720#issuecomment-729762246
type ObjectOf<T> = { [P in keyof T]: T[P] };
```
**Valtio version: 1.2.7
Redux extension version: 2.17.2**

Is this a known issue? Is there a workaround for it maybe?

Thanks

**Comment by Aslemammad** [comment] 2021-12-29 23:59
Could you make a code sandbox repro & mention where's the weird behaviour exactly?

**Comment by hee10k** [comment] 2022-01-03 08:19
It seems to me that Redux devtools and Nextjs(In my case) HMR are related.
Whenever I update the Valtio state code, Redux devtools creates a duplicate store.

![image](https://user-images.githubusercontent.com/6397177/147910675-9350c363-8f4b-4e38-bb50-cfd4226c8e59.png)

**Comment by Aslemammad** [comment] 2022-01-04 17:04
Could you try #307 ?

**Comment by Aslemammad** [comment] 2022-01-04 17:05
in your package.json:
```json
    "valtio": "https://pkg.csb.dev/pmndrs/valtio/commit/84ae5735/valtio"

```

**Comment by Yanivba18** [comment] 2022-01-05 14:52
So, I tried to reproduce it in a code sandbox, and it seems like the issue is actually with redux devtools and not valtio.

I noticed that my stores from different projects keeps showing in redux devtools, regardless of which tab I am on. This makes me believe that the duplication was actually old store instances that for some reason were never deleted from redux devtools.

So for now I'm closing this issue as I don't believe it is connected to valtio. If someone finds some new information on this weird behavior, they are welcome to reopen it - or open an issue for redux (though they might just say that they are not supporting valtio).

**Comment by dai-shi** [comment] 2022-01-05 23:55
I'm a little confused with the current status.

The `createStore` in OP seems correct, so if it's causing some issues, we'd need to look into it.

HMR can be troublesome, which we did overlook.

```js
devtools(state, "store name");
devtools(state, "store name");
```
This ☝️ is expected, so I don't think it's an issue, but I know HMR will cause this 👇 which is an issue.
```js
devtools(originalState, "store name");
devtools(newStateWithHMR, "store name");
```

---
So, is the remaining issue only with HMR? can anyone confirm?

**Comment by Aslemammad** [comment] 2022-01-06 04:33
Yep, You can try codesandbox and see how HMR causes that issue!

**Comment by Yanivba18** [comment] 2022-01-06 14:49
You guys are correct. I tested it again and it does seem to be connected to HMR. 

I added this to my package.json:
`    "valtio": "https://pkg.csb.dev/pmndrs/valtio/commit/84ae5735/valtio"`

Did `npm i` after deleting my node_modules for a clean install. Unfortunately the problem persists in this case:
```typescript
devtools(originalState, "store name");
devtools(newStateWithHMR, "store name");
```

(This is the only way I managed to reproduce this)

**Comment by dai-shi** [comment] 2022-01-09 11:37
I confirmed the HMR issue with https://codesandbox.io/s/react-typescript-forked-cis61?file=/src/App.tsx

It looks like there's a same issue with Redux: https://codesandbox.io/s/react-typescript-forked-cis61?file=/src/App.tsx

Now, I think it's unfortunate that we have this issue, but I don't feel #307 is the right fix. The issue is not only in valtio, but in redux, (and probably zustand and jotai), so it's fundamentally difficult (we may need something like babel plugin.)

While any idea to work around is nice and welcome, I'd mark this as `wontfix` for now and close.

A workaround for us for now is to define a state in a separate file, and unless you edit the file the HMR issue won't happen.

**Closed by dai-shi** 2022-01-09 11:37 UTC
Labels: needs repro
