### ISSUE TITLE
`readonly` considered as a breaking change?

### ISSUE THREAD

**Issue by wiesson** [pmndrs/valtio#327] opened 2022-01-17 12:22 UTC
A `readonly` has been introduced in the recent minor 1.2.9 release

https://github.com/pmndrs/valtio/commit/a983b8b8bfa4bcedeb90774c74bc30270f27931e#diff-b68a2cbc8606fe37f9c2c72867a87ff50a11c2b38a6d9de45a94281f02bf0a4eR252

Is this considered to be a breaking change? The change makes sense to me and it looks useful, but it in my case, I haven't explicitly marked props as `readonly`. My build breaks in ts strict mode and in order to fix it, I have to mark all props as `readonly` (I haven thought much about it before, but to me props are always immutable) where I pass data from `useSnapshot`.

**Comment by dai-shi** [comment] 2022-01-17 12:34
Thanks for reporting.
Hm, I thought it's a proper fix in types, because it's frozen in JS.
But, I overlooked the breaking types in user code.
Let me add a note at least in the release page.

Let's how this is troublesome for others.
If it causes more trouble than benefits, we can consider reverting it.

**Comment by wiesson** [comment] 2022-01-17 12:37
> Let's see how this is troublesome for others.

Good idea! I'll stay on `1.2.8` and until I have added readonly to my props (or  somebody else gives a hint how to fix it 😅)

**Comment by rvirani1** [comment] 2022-01-18 16:17
This also broke my build. I also agree that it is a useful change even though it is painful in the short term to change types across my whole code base. I do foresee this being troublesome for a lot of users. Would it make sense to add a small info section about this in the README?

**Comment by dai-shi** [comment] 2022-01-18 23:06
Thanks for the feedback. I'm not sure if the README is the right place. I added a note in the release note.
I thought about some migration path, but I don't thin we have a way to warn it and pass the build. So, adding a small info makes sense. Maybe at the top of README?

Can you share some small code snippet that breaks with `readonly`. Would love to learn the real cases.

**Comment by rvirani1** [comment] 2022-01-19 00:15
I found that any case where the type of a key is an array of something, i.e. `string[]`. With the new update, I'm forced to change this to `readonly string[]` and make sure anything using or passing that value when read is typed as `readonly string[]` instead of `string[]`.

**Comment by dai-shi** [comment] 2022-01-19 00:22
Yeah, sorry, I know how it's causing the error. My question out of curiosity is how/where you specify `string[]` in your app code.

**Comment by rvirani1** [comment] 2022-01-19 00:50
Let me know if this helps:

```typescript
import { proxy } from 'valtio'

interface ProxyType {
  someKey: readonly string[]
}

const testProxy = proxy({ someKey: [] }) as ProxyType

function doAThing (param: string[]): void {
  console.log(param)
}

// The call below throws this:
// Argument of type 'readonly string[]' is not assignable to parameter of type 'string[]'.
// The type 'readonly string[]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.
doAThing(testProxy.someKey)
```

**Comment by dai-shi** [comment] 2022-01-19 02:44
Thanks. ProxyType shouldn't be readonly.
I guess you use `useSnapshot` (or `snapshot`?), so it's more like this?
```ts
import { proxy, useSnapshot } from 'valtio'

interface ProxyType {
  someKey: string[]
}

const testProxy = proxy<ProxyType>({ someKey: [] })

function doAThing (param: string[]): void {
  console.log(param)
}

  // in component
  const snap = useSnapshot(testProxy)
  doAThing(snap.someKey) // snap.someKey is `readonly string[]`
```

**Comment by dai-shi** [comment] 2022-01-19 02:45
What about using a wrapper hook for gradual migration.
```ts
import { useSnapshot as useSnapshotOrig } from 'valtio'

type DeepWritable<T> = {
  -readonly [P in keyof T]: DeepWritable<T[P]>
}

const useSnapshot = <T extends object>(proxyObject: T) => {
  const snap = useSnapshotOrig(proxyObject)
  return snap as DeepWritable<T>
}
```

See: https://tsplay.dev/NrGJlm

**Comment by mysterybear** [comment] 2022-01-19 14:05
```ts
// store hooks file
export const useHouses = () => {
  const snap = useStoreSnap()
  return [
    snap.houses,
    (input: SetStateAction<Houses>): void => {
      if (typeof input === "function") {
        store.houses = input(store.houses)
      } else {
        store.houses = input
      }
    },
  ] as const
}

// component code
  const houses = useHouses()
  const houseChildren = pipe(
    houses, // ts(2345) error here, I'm using fp-ts pipe and collect
    collect(Ord)((id, house) => (
      <div key={id}>
        <h2>hi</h2>
      </div>
    ))
  )

// houses type
export type Houses = Record<string, House>;
```

What's the idea here, could somebody post an example of how code should look (for setting up the proxy and writing hooks to do operations) so that type-checking passes with this new readonly thing?

**Comment by StephenStrickland** [comment] 2022-01-20 17:25
I'm definitely seeing some weird behavior with this update. Classes that contain `Date` properties get expanded into a giant type declarations. For example:
```ts
class Resource {
   integrationGUID: string;
   createdAt: Date;
   companies: Company[]; // interface declared elsewhere
// ...
}

const resourceStore = proxy({resources: Resource[]}); //impl

```
The stores `resources` type is expanded to the following when using `const {resources} = useSnapshot(resourceStore)`:
![image](https://user-images.githubusercontent.com/6843062/150386551-7d0870db-3abc-4c35-94c8-f6b1e3944332.png)

It's clear that the 1.2.9 update makes all properties `readonly` but IMO this muddies the DX of valtio, especially when dealing with potentially large classes that contain nested data.

And I'm running into weird issues where properties that are typed as arrays of an interface are for some reason throwing TS type issues when passing into generic props like `data: Readonly<T[]>`

```tsx
interface CustomProps<T extends object = {}> {
   data: Readonly<T[]>
}

export function Custom<T extends object = {}>(
  props: CustomProps<T>
) {
   return (//impl);
}
```

Attempting to pass in `resources` to `<Custom data={resources} />` yields this confusing error:
```
Type 'readonly { readonly integrationGUID: string; readonly createdAt: { readonly toString: () => string; readonly toDateString: () => string; readonly toTimeString: () => string; readonly toLocaleString: { (): string; (locales?: string | string[] | undefined, options?: DateTimeFormatOptions | undefined): string; }; ... 3...' is not assignable to type 'readonly Resource[]'.
  Type '{ readonly integrationGUID: string; readonly createdAt: { readonly toString: () => string; readonly toDateString: () => string; readonly toTimeString: () => string; readonly toLocaleString: { (): string; (locales?: string | string[] | undefined, options?: DateTimeFormatOptions | undefined): string; }; ... 39 more .....' is not assignable to type 'Resource'.
    Types of property 'companies' are incompatible.
      The type 'readonly { readonly integrationGUID: string; readonly name: string; }[]' is 'readonly' and cannot be assigned to the mutable type 'Company[]'.ts(2322)
```
_note: I'm mid migration of my codebase to valtio, if anyone has an obvious fix to the above issue, please let me know. thanks._

The combination of running into weird generic TS issues and the `1.2.9` update forcing everything to be typed `readonly` making snapshot types difficult to read, reduces the DX that `valtio` strives to offer. I love this library, but I'm going to have to remain on 1.2.8 until I have time to dig into the implications of the `readonly` update. And if there's some common best practice that I'm missing, please let me know. I am new to valtio.

**Comment by mysterybear** [comment] 2022-01-20 18:07
https://codesandbox.io/s/github/mysterybear/valtio-play

@dai-shi should this be throwing a type error? I've wrapped the `HouseT` prop type with the `Readonly` utility type

**Comment by mysterybear** [comment] 2022-01-20 18:20
Ah, someone on TS Discord helped me out

```ts
type HouseViewProps = {
  house: DeepResolveType<HouseT>
}
```

Maybe we could use some docs on this `DeepResolveType` utility type?

**Comment by dai-shi** [comment] 2022-01-20 22:37
Thanks for reporting. I notice that this is a larger issue than I expected. It's not just about `readonly` change. It reveals the potential design issue.

So, we didn't think `DeepResolveType` as public API (not directly exported from index.ts). Somebody already reported about the difficulty of typing caused by `DeepResolveType` (not related with `readonly`.) #292 
The solution was:
```ts
  const { houses } = useSnapshot(store) as HouseT
```

For most users, DeepResolveType didn't make much sense because it was only useful when we use Suspense features. `readonly` changed this...

I would like to fix this problem (both of them) somehow. It may require a help from TS experts. There's one thing I want to solve: https://twitter.com/dai_shi/status/1480523055105724419

**Comment by mysterybear** [comment] 2022-01-21 05:59
@dai-shi someone on TS Discord says
> I think the pattern he's looking for is impossible, trying to contain an explicit reference to a type without exporting it.

**Comment by dai-shi** [comment] 2022-01-21 08:56
That's good to know. Then, I will give up using `const enum`. Let me create a new PR, which technically solves #292, but it doesn't help this issue.

**Comment by privatenumber** [comment] 2022-02-07 22:21
I don't mind the `readonly` change (although I agree this should've been a major release).
But I wonder if you should also export the `Snapshot` type utility to recursively convert types to readonly.
Otherwise, I believe I have to create or import a separate `DeepReadOnly` utility type.

**Comment by dai-shi** [comment] 2022-02-07 22:45
Thanks for the feedback.

> (although I agree this should've been a major release).

(I feel like I shouldn't have merged that PR, if I knew this.)

> I have to create or import a separate DeepReadOnly utility type.

but, that's what I'm suggesting if you _really_ need it. I _really_ want to hide `Snapshot` type as an implementation detail.

**Comment by dai-shi** [comment] 2022-02-10 11:47
Hi, my suggestion in your case is this (or [that](https://github.com/pmndrs/valtio/issues/327#issuecomment-1016026509)):
```js
const snap = useSnapshot(state) as typeof state
```
Does it work? Maybe we should add this in readme.

**Comment by IljaDaderko** [comment] 2022-02-10 11:52
> Hi, my suggestion in your case is this (or [that](https://github.com/pmndrs/valtio/issues/327#issuecomment-1016026509)):
> 
> ```js
> const snap = useSnapshot(state) as typeof state
> ```
> 
> Does it work? Maybe we should add this in readme.

Does the trick, but feels like a "hack around" if that makes sense. Would it be viable to instead introduce something like `useReadonlySnapshot` for those who want these strict typings and perhaps enforce it over `useSnapshot` via valtios eslint plugin with added rule?

I think there will be a lot of use cases where user's don't need to mutate these values, yet they have to be passed on to an api or something else that doesn't expect that readonly addition.

**Comment by dai-shi** [comment] 2022-02-10 11:58
I prefer to make it the other way around: `useSnapshotLooselyTyped`.

> I think there will be a lot of use cases where user's don't need to mutate these values, yet they have to be passed on to an api or something else that doesn't expect that readonly addition.

I don't disagree with this. It's something I really overlooked when reviewing the PR. But, there are opposite opinions from users. So, at least from the library perspective, it should use _correct_ typing.

**Comment by IljaDaderko** [comment] 2022-02-10 12:02
That makes sense, perhaps `useProxy` can be re-used for this? To make naming nicer. This might also help with upgrading from older versions of valtio without that babel macro?

**Comment by dai-shi** [comment] 2022-02-10 13:00
`useProxy` macro is totally a different one after v1, so we shouldn't mix it.

currently I'm leaning to a recipe in readme rather than an exported function in utils, because there could be variations for various use cases.

Let's see what others think.

**Comment by Elia-Darwish** [comment] 2022-02-10 13:14
We have a project where we are using a generated API types where `readonly` is not supported, which made the process even longer. But we finally have it done!!

I just wanted to share a Typescript snippet that we used to ease the process...

```ts
declare type AnyFunction = (...args: unknown[]) => unknown

export type DeepReadonly<T> = T extends (infer R)[]
  ? DeepReadonlyArray<R>
  : T extends AnyFunction
  ? T
  : T extends object
  ? DeepReadonlyObject<T>
  : T

export type DeepReadonlyArray<T> = ReadonlyArray<DeepReadonly<T>>

export type DeepReadonlyObject<T> = {
  readonly [P in keyof T]: DeepReadonly<T[P]>
}
```

@dai-shi  would it maybe be helpful to export a similar utility to ease the process of migration?

**Comment by dai-shi** [comment] 2022-02-11 05:16
You don't need such a complicated type util.

https://tsplay.dev/mZry9m

<img width="523" alt="image" src="https://user-images.githubusercontent.com/490574/153541003-ad6f0d33-b2be-4e29-9eed-0006ee8af5e8.png">


I hope eventually TypeScript supports it: https://github.com/microsoft/TypeScript/issues/13923

---

Overall, I think people wouldn't necessarily want to revert `readonly` change. It's technically type breaking, so, to mitigate such cases, let's add a note in readme. Will open a PR.

**Comment by dai-shi** [comment] 2022-02-11 07:19
Folks, I've got a better solution! With #359, we can do [Module Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation).

https://codesandbox.io/s/react-typescript-forked-qphpi?file=/src/App.tsx:46-125
```ts
declare module "valtio" {
  function useSnapshot<T extends object>(p: T): T;
}
```

**Closed** 2022-02-12 13:09 UTC

**Comment by naivefun** [comment] 2022-05-07 02:44
> Module Augmentation

@dai-shi  this is causing new problem, looks it overwrite export deifinition instead of argumentation:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/10683378/167234893-71ac8b00-63d4-491e-b62a-a8fb1bac7652.png">

**Comment by dai-shi** [comment] 2022-05-31 22:16
We have a PR #458 open to document it.

**Comment by dai-shi** [comment] 2022-09-19 07:22
#458 is closed but the discussion there might be valuable.

**Comment by some-dudes-work-account** [comment] 2023-06-16 00:12
Stumbled on this as well earlier this week. I know the discussion has long been over but let me contribute anyway

> Can you share some small code snippet that breaks with readonly. Would love to learn the real cases.

Here's one such case: [Typescript Playground Link](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAggdiAYgVzgY2ASwPZygXigAoA6MgQwCcBzAZwC4pyEBtAXQEoCA+JhAbgBQoSFAAiECGABKEcgBNcAGxAAeACq9C6qBAAewCHHm1YCFOiy4oAfig7GAbyiU5iuCqgsA0lEx4AawgQbAAzezZGCSlZBWU1dR82bn4oAF8hYXBoAElDAFsCKGdMeUY4ZHyAIwhKABooPXLKmspUkGbq2vShEWgAWWRgciqlCHVsosdBKFm-AoYoPIh89jrBNMEs0Vj3FQnRQmcAemOoWnJ86HJTaJk3eNVB4dHx7O4ZudOoT9nvzGAAHJTMAABaYUyuOIeEBQMHkYBQKpQgIg8FwOgNGCUSjkNTMEC8X5Qb5zMnkskAN2JUL2sIBK0WtPixWJZOZML8ZSgFS6bTZcw5niaPJatSEFNmQthHVFfIlczS7CEm0EoVQGBweDQuFolQgtGeIzGRGwVQAVowja8DhAuM5XMBkJQ8GbzSQGflaKlNurLFqoDq4HqrrRdvFTRbGOGYbb7S4IE6XVA3R6Fj6tkHaIj8kNjRAAPJRqDWsa2qbzRmMdg9QRZxHSouWqAx-aTI6Vr3Vti1uu6-WGvOvIi5l5jJscIRZgeliBERsWycks4Ad0wSiUcNBlGwK4aNTQ5GQtGg0sDzEBiJqUGPEHkfjwYCU5DQ0DCUFH+cz-dDrZAI6HcdFynH8DT-ecHhhCdMiAA) 

In my case method consuming the value was defined in another module and it uses auto-generated type annotations of server responses from yet another module, which don't have readonly keywords anywhere in them. 

I like the idea of having readonly properties on objects returned from `useSnapshot` and have awaited promise values unwrapped. And the only thing that TS didn't like seems to be when we're attempting to pass `ReadonlyArray`'s in place of `Array`'s (same for `readonly` tuples), so rather than re-defining it as
```ts
function useSnapshot<T extends object>(p: T): T;
```
as was suggested above I went for a different approach and just undid readonly flags on arrays. But in order to do this I had to rely on the "internal" export

```ts
// somewhere in my lib-env.d.ts

import 'valtio'; // probably unnecessary because of the next line
import { INTERNAL_Snapshot } from 'valtio';

type AnyFunction = (...args: any[]) => any;
type AnyArray = readonly unknown[];
type MutableArrays<T> = T extends AnyFunction ? T :
  T extends AnyArray
    ? { -readonly [K in keyof T]: MutableArrays<T[K]> }
    : { [K in keyof T]: MutableArrays<T[K]> }; // prettier-ignore

declare module 'valtio' {
  function useSnapshot<T extends object>(p: T): MutableArrays<INTERNAL_Snapshot<T>>;
}
```

Personally I would have prefer that to be default behaviour. It defeats the purpose, but if this is something that everybody has to dance around, maybe it is worth making the default

**Comment by dai-shi** [comment] 2023-06-16 01:28
> > Can you share some small code snippet that breaks with readonly. Would love to learn the real cases.
> 
> Here's one such case: [Typescript Playground Link](https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAggdiAYgVzgY2ASwPZygXigAoA6MgQwCcBzAZwC4pyEBtAXQEoCA+JhAbgBQoSFAAiECGABKEcgBNcAGxAAeACq9C6qBAAewCHHm1YCFOiy4oAfig7GAbyiU5iuCqgsA0lEx4AawgQbAAzezZGCSlZBWU1dR82bn4oAF8hYXBoAElDAFsCKGdMeUY4ZHyAIwhKABooPXLKmspUkGbq2vShEWgAWWRgciqlCHVsosdBKFm-AoYoPIh89jrBNMEs0Vj3FQnRQmcAemOoWnJ86HJTaJk3eNVB4dHx7O4ZudOoT9nvzGAAHJTMAABaYUyuOIeEBQMHkYBQKpQgIg8FwOgNGCUSjkNTMEC8X5Qb5zMnkskAN2JUL2sIBK0WtPixWJZOZML8ZSgFS6bTZcw5niaPJatSEFNmQthHVFfIlczS7CEm0EoVQGBweDQuFolQgtGeIzGRGwVQAVowja8DhAuM5XMBkJQ8GbzSQGflaKlNurLFqoDq4HqrrRdvFTRbGOGYbb7S4IE6XVA3R6Fj6tkHaIj8kNjRAAPJRqDWsa2qbzRmMdg9QRZxHSouWqAx-aTI6Vr3Vti1uu6-WGvOvIi5l5jJscIRZgeliBERsWycks4Ad0wSiUcNBlGwK4aNTQ5GQtGg0sDzEBiJqUGPEHkfjwYCU5DQ0DCUFH+cz-dDrZAI6HcdFynH8DT-ecHhhCdMiAA)

To me, it looks like exactly the case we want to warn.

> In my case method consuming the value was defined in another module and it uses auto-generated type annotations of server responses from yet another module, which don't have readonly keywords anywhere in them.

Yeah, that's problem, but it's only the user who know it. So, `as` should be the right solution.

> But in order to do this I had to rely on the "internal" export

In the next version, we don't unwrap promises, so the type should be simpler. We may revisit about considering exporting the snapshot type.

> Personally I would have prefer that to be default behaviour. It defeats the purpose, but if this is something that everybody has to dance around, maybe it is worth making the default

fwiw, the change is requested from a user, and it's correct typing and allows to catch errors at compile time. At this point, there's no reason to go back.

**Comment by dai-shi** [comment] 2024-02-16 23:31
I didn't know it was possible.

https://tsplay.dev/m3q5qw

<img width="346" alt="image" src="https://github.com/pmndrs/valtio/assets/490574/dd7812e4-de32-4d01-a910-b217b45bef02">

Seems like it's already supported in TS4.7.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#instantiation-expressions

Thanks for sharing!

**Comment by dai-shi** [comment] 2024-02-18 04:43
And this: https://tsplay.dev/WPJZZN

<img width="562" alt="image" src="https://github.com/pmndrs/valtio/assets/490574/e141c082-afe8-40a0-83b0-03966c5e5b1f">

**Comment by Noitidart** [comment] 2024-03-15 03:55
> fyi for others who found this thread, you can't add this module augmentation in `decs.d.ts` — it will override the entire module def — can add it in any other regular ts file, tho

Thank you, this was causing me problems as well. I put it in the index.ts file of app entry.

**Comment by louhaojie99** [comment] 2024-08-12 09:34
```
import { proxy, useSnapshot } from 'valtio';

type DeepWritable<T> = {
  -readonly [P in keyof T]: DeepWritable<T[P]>;
};

const initialState = Object.freeze({
  message: undefined as string | undefined,
  list: [] as
    | Array<{
        name: string;
        children: { name: string }[];
      }>
    | undefined,
});

export type InitialState = DeepWritable<typeof initialState>;

const state = proxy(initialState);

export const updateStateModel = (updatedState: Partial<InitialState>) => {
  Object.keys({ ...updatedState }).forEach(key => {
    state[key] = updatedState[key];
  });
};

export const useStateModel = () => useSnapshot<InitialState>(state) as InitialState;

const Demo = () => {
  const { list } = useStateModel();

  updateStateModel({ list }); // No more readonly trouble
};

```

**Comment by nadaru-fr** [comment] 2024-12-20 09:46
> To use the same deep-readonly method as the library itself (without re-implementing it as suggested above), I just did this and it seems to work as expected:
> 
> ```ts
> type ReadonlyCat = ReturnType<typeof useSnapshot<Cat>>;
> ```

Or `Snapshot<Cat>` :) ?
